# Source of truth for Spark in Docker and Kubernetes.
spark.master                       k8s://https://kubernetes.default.svc
spark.kubernetes.namespace         data-platform
spark.kubernetes.authenticate.driver.serviceAccountName spark
spark.eventLog.enabled             true
spark.eventLog.dir                 hdfs://hdfs-namenode:8020/spark/eventlog
spark.history.fs.logDirectory      hdfs://hdfs-namenode:8020/spark/eventlog
spark.serializer                   org.apache.spark.serializer.KryoSerializer
spark.sql.adaptive.enabled         true
spark.sql.shuffle.partitions       48
spark.network.crypto.enabled       true
spark.authenticate                 true
spark.ui.reverseProxy              false
