---
plugin: amazon.aws.aws_ec2
regions:
  - eu-west-1
filters:
  tag:cluster: data-platform
  instance-state-name: running
groups:
  k3s_server: "'server' in tags.Name"
  data_nodes:  "'data' in tags.Name"
compose:
  ansible_host: public_ip_address
keyed_groups:
  - key: tags.role
    prefix: role
