apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patches/storageclass.yaml
    target:
      kind: StatefulSet
      name: opensearch-data
  - path: patches/storageclass.yaml
    target:
      kind: StatefulSet
      name: hdfs-datanode
  - path: patches/storageclass.yaml
    target:
      kind: StatefulSet
      name: hdfs-journalnode
  - path: patches/storageclass.yaml
    target:
      kind: StatefulSet
      name: hdfs-namenode
  - path: patches/storageclass.yaml
    target:
      kind: StatefulSet
      name: zookeeper

commonLabels:
  environment: local
  - path: patches/resources-small.yaml
    target:
      kind: StatefulSet
      name: opensearch-master
  - path: patches/resources-small.yaml
    target:
      kind: StatefulSet
      name: opensearch-data
