apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patches:
  - path: patches/storageclass.yaml
  - path: patches/resources-small.yaml

commonLabels:
  environment: local
