---
plugin: azure.azcollection.azure_rm
include_vm_resource_groups:
  - data-platform-rg
groups:
  k3s_server: "'server' in name"
  data_nodes:  "'data' in name"
compose:
  ansible_host: public_ipv4_address
