apiVersion: v1
kind: ResourceQuota
metadata:
  name: data-platform-quota
  namespace: data-platform
spec:
  hard:
    pods:                   "40"
    requests.cpu:           "8"
    limits.cpu:             "16"
    requests.memory:        "16Gi"
    limits.memory:          "24Gi"
    persistentvolumeclaims: "24"
    requests.storage:       "500Gi"
    services:               "24"
    configmaps:             "36"
    secrets:                "24"
