# ── Service TCP ───────────────────────────────────────────────────────────────
# FIX : K8s does not support the same port number with different protocolss
# in a single Service. Splitting TCP and UDP into two separate Services.
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: data-platform
  labels:
    app: logstash
  annotations:
    # Prometheus scraping (if Prometheus Operator deployed in the cluster)
    prometheus.io/scrape: "true"
    prometheus.io/port:   "9600"
    prometheus.io/path:   "/"
spec:
  type: ClusterIP
  selector:
    app: logstash
  ports:
    - name: tcp-input
      port: 5000
      targetPort: 5000
      protocol: TCP
    - name: beats
      port: 5044
      targetPort: 5044
      protocol: TCP
    - name: http-input
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: api
      port: 9600
      targetPort: 9600
      protocol: TCP
---
# ── Separate UDP Service ────────────────────────────────────────────────────────
apiVersion: v1
kind: Service
metadata:
  name: logstash-udp
  namespace: data-platform
  labels:
    app: logstash
spec:
  type: ClusterIP
  selector:
    app: logstash
  ports:
    - name: udp-input
      port: 5000
      targetPort: 5000
      protocol: UDP
