apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

# StorageClass patch: GCP pd-ssd
patches:
  - path: patches/storageclass.yaml

commonLabels:
  environment: gcp
