#!/usr/bin/env bash
# ══════════════════════════════════════════════════════════════════════════════
# configure-domain.sh — generates kustomize Ingress patches + ClusterIssuer
# ══════════════════════════════════════════════════════════════════════════════
# Usage : bash scripts/configure-domain.sh <PROVIDER> <DOMAIN> [EMAIL]
#   PROVIDER : gcp | aws | azure
#   DOMAIN   : mycompany.com
#   EMAIL    : ops@mycompany.com  (default: admin@DOMAIN)
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

LIB="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/common.sh"
[ -f "${LIB}" ] && source "${LIB}" || { echo "ERREUR : scripts/lib/common.sh not found"; exit 1; }
ensure_repo_root
load_env

PROVIDER="${1:-${PROVIDER:-}}"
DOMAIN="${2:-${DOMAIN:-}}"
EMAIL="${3:-${ACME_EMAIL:-admin@${DOMAIN:-}}}"

usage() {
  echo "Usage: bash scripts/configure-domain.sh <PROVIDER> <DOMAIN> [EMAIL]"
  echo "  bash scripts/configure-domain.sh gcp mycompany.com ops@mycompany.com"
  echo "  .env variables accepted: PROVIDER, DOMAIN, ACME_EMAIL"
  exit 1
}

# ── Validation des inputs (SOLID-S) ──────────────────────────────────────────
[ -z "${PROVIDER}" ] && { log_err "PROVIDER requis"; usage; }
[ -z "${DOMAIN}"   ] && { log_err "DOMAIN requis";   usage; }

# Special case: local provider has no external Ingress
if ! provider_has_dns_ingress "${PROVIDER}"; then
  echo "INFO : provider '${PROVIDER}' — kubectl port-forward used, no Ingress DNS."
  exit 0
fi

validate_provider "${PROVIDER}" || exit 1
validate_domain   "${DOMAIN}"   || exit 1

# Email: derive from DOMAIN if absent, then validate
EMAIL="${EMAIL:-admin@${DOMAIN}}"
validate_email "${EMAIL}" || exit 1

OVERLAY_DIR="k8s/overlays/${PROVIDER}"
PATCH_FILE="${OVERLAY_DIR}/patches/ingress-domain.yaml"
CERTMGR_FILE="k8s/base/cert-manager/cluster-issuer-configured.yaml"

if [[ ! -d "${OVERLAY_DIR}" ]]; then
  log_err "Overlay not found : ${OVERLAY_DIR}"
  exit 1
fi

log_step "Ingress domain configuration : ${PROVIDER} → ${DOMAIN}"

# ── 1. Patch Ingress kustomize ────────────────────────────────────────────────
cat > "${PATCH_FILE}" << EOF
# Generated by scripts/configure-domain.sh — DO NOT COMMIT
# Domain : ${DOMAIN} | Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opensearch-dashboards-ingress
  namespace: data-platform
spec:
  tls:
    - hosts:
        - dashboards.${DOMAIN}
      secretName: dashboards-tls-cert
  rules:
    - host: dashboards.${DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: { name: opensearch-dashboards, port: { number: 5601 } }
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yarn-ui-ingress
  namespace: data-platform
spec:
  tls:
    - hosts:
        - yarn.${DOMAIN}
      secretName: yarn-tls-cert
  rules:
    - host: yarn.${DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: { name: yarn-resourcemanager, port: { number: 8088 } }
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hdfs-ui-ingress
  namespace: data-platform
spec:
  tls:
    - hosts:
        - hdfs.${DOMAIN}
      secretName: hdfs-tls-cert
  rules:
    - host: hdfs.${DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: { name: hdfs-namenode, port: { number: 9870 } }
EOF
log_ok "Patch Ingress generated : ${PATCH_FILE}"

# ── 2. ClusterIssuer cert-manager ─────────────────────────────────────────────
cat > "${CERTMGR_FILE}" << EOF
# Generated by scripts/configure-domain.sh — DO NOT COMMIT
# Email : ${EMAIL} | Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Apply after running bootstrap-cert-manager.sh :
#   kubectl apply -f ${CERTMGR_FILE}

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ${EMAIL}
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ${EMAIL}
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
      - http01:
          ingress:
            class: nginx
EOF
log_ok "Configured ClusterIssuer : ${CERTMGR_FILE}"

# ── 3. Persist to .env ─────────────────────────────────────────────────────
if [[ -f ".env" ]]; then
  { grep -v "^DOMAIN=\|^ACME_EMAIL=" .env; \
    echo "DOMAIN=${DOMAIN}"; echo "ACME_EMAIL=${EMAIL}"; } > /tmp/.env.new && mv /tmp/.env.new .env
  log_ok "DOMAIN + ACME_EMAIL updated in .env"
fi

log_done "Domain configured : ${DOMAIN}"
echo ""
echo "  DNS records to create (A records → external LoadBalancer IP) :"
echo "    dashboards.${DOMAIN}"
echo "    yarn.${DOMAIN}"
echo "    hdfs.${DOMAIN}"
echo ""
echo "  Next steps :"
echo "    1. make bootstrap-cert-manager ACME_EMAIL=${EMAIL} ARGS=--staging"
echo "    2. kubectl apply -f ${CERTMGR_FILE}"
echo "    3. PROVIDER=${PROVIDER} make deploy"
